services:
  - type: web
    name: ai-content-api
    runtime: python
    buildCommand: pip install -r requirements.txt
    startCommand: uvicorn main:app --host 0.0.0.0 --port $PORT
    envVars:
      - key: PORT
        value: 10000
      - key: OPENROUTER_API_KEY
        value: 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
      - key: STRIPE_PUBLISHABLE_KEY
        value: pk_test_51TGJOt8AZvg3KupHOrjoVvSbTt6zHcIIjsbl0asgzoVQBP7OgXwNSgeZigvxm6MQInsWEvBqKaK15SwyWjtHYbFR00k8CVHazf
      - key: STRIPE_SECRET_KEY
        value: sk_test_51TGJOt8AZvg3KupHWmPh3LP0Ai4QUuSz8iHuA0bnUPqaXHLSionaDmpGjp2DJeioGOVDmoUbCIwHAGgJ6uTN4X7F00QnB9ozcM
      - key: STRIPE_WEBHOOK_SECRET
        value: whsec_BxBBWYTvI2LLZIrGLRwmOc7kU5BFhHGs